### PR TITLE
Depthimage to laserscan dev

### PR DESCRIPTION
**Pull request by jasonjabbour**
Hi! Getting closer to finalizing the depth image to laserscan benchmark.

image

I had a quick question about how we are measuring power in the grey-box methodology. Could you give me an example about what I could set the [POWER_LIB ](https://github.com/jasonjabbour/benchmarks/blob/e9509bc6ca2d8e4677f76217ea68409fff4ae509/benchmarks/perception/a6_depthimage_to_laserscan/launch/trace_a6_depthimage_to_laserscan_power.launch.py#L12) variable to? Also, I wanted to get a better understanding about how the [robotcore-power package ](https://github.com/jasonjabbour/benchmarks/blob/e9509bc6ca2d8e4677f76217ea68409fff4ae509/benchmarks/perception/a6_depthimage_to_laserscan/launch/trace_a6_depthimage_to_laserscan_power.launch.py#L38-L44) measures power, but I can't seem to find the source code of this package. Could you point me in the right direction?

Thanks so much!!

### CODE REVIEW

**Comment by jasonjabbour** [comment]
@vmayoral This benchmark is now completed and ready to be ran on your hardware! Please take a look and let me know if anything needs to be improved. This benchmark evaluates the DepthImageToLaserScanROS node from the [depthimage_to_laserscan](https://github.com/ros-perception/depthimage_to_laserscan/tree/ros2) package. It also incorporates a preprocessing pipeline that converts left and right stereo images into a disparity map using the [stereo_image_proc](https://github.com/ros-perception/image_pipeline/tree/humble/stereo_image_proc) package that was previously benchmarked in the [a3 benchmark](https://github.com/robotperf/benchmarks/tree/main/benchmarks/perception/a3_stereo_image_proc). The disparity map produced by this node is then converted into a depth image before undergoing the final conversion into a laser scan.

Images of the computational graphs can be found in the imgs directory or [here](https://github.com/jasonjabbour/benchmarks/tree/depthimage-to-laserscan-dev/benchmarks/perception/a6_depthimage_to_laserscan/imgs) 

Thanks!

**Comment by jasonjabbour** [comment]
Made an improvement to the laserscan_output_component node by creating robotperf_laserscan_output_cb_init/fini tracepoints instead of using the robotperf_image_output_cb_init/fini tracepoints.

**Comment by seowwj** [comment]
Hi @jasonjabbour, I see that you've mentioned about the `robotcore-power` package that measures power. Did you manage to find out how it does so? I'm also looking for the same thing and would appreciate any help understanding that part 😄 

Thanks!

**Comment by jasonjabbour** [comment]
Hi @seowwj thanks for your interest. robotcore-power is a package that was developed by the acceleration robotics team and has not been open sourced. Please see [this ](https://github.com/robotperf/benchmarks/issues/237#issuecomment-1665072947) for more information!

**Pull request closed without merging**
