### PR TITLE
Refactor benchmark analysis

### PR DESCRIPTION
**Pull request by mcres**
Addresses issue #24 

Work is still in progress. Here are the subtasks to accomplish:
- [x] Create a `benchmark_utilities` package 
- [x] Refactor `a1_perception_2nodes` 
- [x] Refactor `a1_perception_2nodes` FPGA version
- [x] Refactor `a2_rectify` 
- [x] Refactor `a3_stereo_image_proc` 
- [x] Refactor `a5_resize` 

New tasks:
- [ ] Validate `a1_perception_2nodes` with real data from FPGA

### CODE REVIEW

**Comment by mcres** [comment]
@vmayoral would you mind taking a quick look and providing early feedback?

Specially on how to provide the target configuration. My proposal is to pass it as dictionaries to the `BenchmarkAnalyzer` class: https://github.com/mcres/benchmarks/blob/5d6ea2d42c89a5d82392d2d82d4c33f66c0291fa/benchmarks/perception/a1_perception_2nodes/launch/analyze_a1_perception_2nodes.launch.py#L33

**Comment by mcres** [comment]
Up to this commit, I've refactored and replicated exactly what we had with the duplicated analysis launch files.

Some issues that need to be solved:
1. Plotting is only integrated for `a1_perception_2nodes` benchmark. The reason is that currently, computation of the times between specific trace timestamps is hardcoded (see [this](https://github.com/mcres/benchmarks/blob/5cba451c3611ef046e7962033585cc5681c32f77/benchmarks/other/benchmark_utilities/benchmark_utilities/analysis/__init__.py#LL432C18-L432C18)).
2. We currently configure the targets to be analyzed with the `add_target` method. However, it can be cumbersome and repetitive (see [this](https://github.com/mcres/benchmarks/blob/refactor_benchmark_utilities/benchmarks/perception/a1_perception_2nodes/launch/analyze_a1_perception_2nodes.launch.py#L35)).
3. The markdown `statistics` returned by the class is computed between two given intervals. This is currently hardcoded as well, since `a3` differs from the rest (see [this](https://github.com/mcres/benchmarks/blob/5cba451c3611ef046e7962033585cc5681c32f77/benchmarks/other/benchmark_utilities/benchmark_utilities/analysis/__init__.py#L912)).
4. Some methods are only executed depending on the accelerator type (see [this](https://github.com/mcres/benchmarks/blob/5cba451c3611ef046e7962033585cc5681c32f77/benchmarks/other/benchmark_utilities/benchmark_utilities/analysis/__init__.py#LL1141C49-L1141C49)), which perhaps could be better implemented than if-else conditions?
5. `analyze_traces` can be refactored even more (e.g splitting it's tasks into more functions to improve readability)

To address 1 and 2, and for the sake of generalizing the analysis to future traced graphs with random nodes, I think we could do something like:
- Define some custom classes that represent important nodes in the graph (e.g. `RectifyImageTrace`). As benchmarks are created for different applications, these classes can be created as we need them.
- This classes would have information about the traces of the node (e.g. `callback_start` + `image_proc_rectify_cb_init` + `image_proc_rectify_init` + `image_proc_rectify_fini` + `image_proc_rectify_cb_fini` + `callback_end`) and their color and other properties.
- Define a `TargetChain` class that can be configured by the user (e.g. the target can be composed of a `RectifyImageTrace` and a `ResizeImageTrace`)
- With these classes, we could more easily both define the `target_chain` and configure the plotting intervals in a generic way.  

I think it would be a good idea to discuss these points and define priorities before moving on and adding more code.

**Comment by alexMarFar** [comment]
@mcres thank you for working on this issue. I think your proposal will work greatly. I have added some additional comments below:

To adress 1 and 2, you proposed:
> * Define some custom classes that represent important nodes in the graph (e.g. `RectifyImageTrace`). As benchmarks are created for different applications, these classes can be created as we need them.
> * This classes would have information about the traces of the node (e.g. `callback_start` + `image_proc_rectify_cb_init` + `image_proc_rectify_init` + `image_proc_rectify_fini` + `image_proc_rectify_cb_fini` + `callback_end`) and their color and other properties.
> * Define a `TargetChain` class that can be configured by the user (e.g. the target can be composed of a `RectifyImageTrace` and a `ResizeImageTrace`)
> * With these classes, we could more easily both define the `target_chain` and configure the plotting intervals in a generic way.

I think this approach should also be used for the input and output:
* InputTrace: `callback_start` + `robotperf_image_input_cb_init` + `robotperf_image_input_cb_fini` + `callback_end` 
* OutputTrace: `callback_start` + `robotperf_image_output_cb_init` + `robotperf_image_input_cb_fini` + `callback_end` 

In this way, the `TargetChain` class can by default include these traces as the first and last elements on the list. This list would then be iterated while adding the targets through the method "add_target".

> 3. The markdown `statistics` returned by the class is computed between two given intervals. This is currently hardcoded as well, since `a3` differs from the rest (see [this](https://github.com/mcres/benchmarks/blob/5cba451c3611ef046e7962033585cc5681c32f77/benchmarks/other/benchmark_utilities/benchmark_utilities/analysis/__init__.py#L912)).

It could be possible to add `first_target` as a field in the class `TargetChain`.

> 4. Some methods are only executed depending on the accelerator type (see [this](https://github.com/mcres/benchmarks/blob/5cba451c3611ef046e7962033585cc5681c32f77/benchmarks/other/benchmark_utilities/benchmark_utilities/analysis/__init__.py#LL1141C49-L1141C49)), which perhaps could be better implemented than if-else conditions?

Agree, but maybe not the main priority at the moment.

> 5. `analyze_traces` can be refactored even more (e.g splitting it's tasks into more functions to improve readability)

Agree. Although since there will be other metrics in the future in addition to "latency" there could be other options such as reorganizing by methods and functionalities or by the specific metric of study. What do you think?

**Comment by mcres** [comment]
I've noticed something weird on the results. I must've made something wrong in previous changes.
Seems that the `Benchmark Mean` and `Mean` computations are not okay now.

Here's the analysis for `a2` before any refactoring (right):
```bash
 |   | Benchmark Mean | Benchmark RMS | Benchmark Max  | Benchmark Min | Mean | RMS | Max | Min | 
 | --- | --- | --- | --- | --- | --- | --- | --- | --- | 
 | RobotPerf benchmark | **5.98** ms | **6.57** ms | **26.00** ms | **1.86** ms | **6.49** ms | **7.10** ms | **27.30** ms | **2.15** ms | 
```

For the same tracefile, here's the analysis of `a2` up to this commit (wrong):
```bash
 |   | Benchmark Mean | Benchmark RMS | Benchmark Max  | Benchmark Min | Mean | RMS | Max | Min | 
 | --- | --- | --- | --- | --- | --- | --- | --- | --- | 
 | RobotPerf benchmark | **6.57** ms | **6.57** ms | **26.00** ms | **1.86** ms | **7.10** ms | **7.10** ms | **27.30** ms | **2.15** ms | 
```
The same happens for the rest of the benchmarks. The timing pipeline is okay though.

Let me find the problem. Hopefully this will happen less once we have a CI/CD pipeline

**Comment by vmayoral** [comment]
@mcres edited your comment above, note you can drop tables directly in Markdown.

As for the results, having slighly different mean values is totally ok, and expected. Even if using the same machine, processing workloads vary over time within your machine depending on what you're doing on it, which leads to slighly mean variations. This also depends on the amount of samples (or dataset) used. If you're just throwing the same rosbag over an over (in a loop), mean results will be affected by this also.

This is the reason why we care about worse case scenario (the Max values).

**Comment by vmayoral** [comment]
> You're right, but the steps for obtaining the two tables were:
> 
>     1. Run a trace launch file and obtain the traces in `~/.ros/tracing/a2_rectify/`
> 
>     2. With traces obtained in `1`, run the analysis launch file _before_ refactoring and obtain table 1
> 
>     3. With traces obtained in `1`, run the analysis launch file _after_ refactoring and obtain table 2
> 
> 
> Thus the results must be exactly the same in this case.

I see, thanks for clarifying. Makes sense. Indeed, I'd also expect the same result after refactoring if the dataset doesn't change. Refactoring the analysis scripts shouldn't affect results as we're relaying on the same tracefiles.

**Comment by mcres** [comment]
Silly error fixed, now the markdown results are the same before and after refactoring. Sorry for the inconvenience.

Please, be careful if you're comparing timelines printed on the console. There are several methods for printing, comparison should be made only when the same method is called (see [here](https://github.com/mcres/benchmarks/blob/01c264ee95508966aed4f1e11fa7c0b27e930d6f/benchmarks/other/benchmark_utilities/benchmark_utilities/analysis/__init__.py#L1155-L1160)). Just mentioning it so you don't repeat the same error as me ;-)

I'd be happy to close this PR if you agree.

**Pull request merged**
